## PROBLEM STATEMENT
As the Electric vehicle usage increases the usage of electricity also increases .
So the task is to find predict whether the usage leads to which category of risk.and it is categorized in a binary way.
so this is a binary classification problem.So models like Logistic Regression,SVC and Random Forest models d

#  1.Understanding the Problem

Goal: Predict whether an EV user is at high risk of default (High_Default_Risk).
Type: Binary classification (0 = Low Risk, 1 = High Risk)
Input: Demographics, EV type, battery capacity, charging sessions, costs, distance traveled, etc.
Metric: F1-score or ROC-AUC (because classes may be imbalanced)

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("EV Charging Behavior Dataset.csv")
df.head()

,User_ID,Age,City_Tier,EV_Type,Battery_Capacity_kWh,Charging_Sessions_Per_Month,Avg_Charge_Cost,Distance_Travelled_Per_Month,Income_Level,Loan_Taken,Missed_Payments_Last_6M,Tenure_Months,Charging_Location_Type,App_Usage_Score,Charger_Working_Status,Charging_Time_Minutes,High_Default_Risk,Charging_Efficiency_Index
0,1,59,Tier3,5KW,40.7,19,325.10,1702,Low,0,2,1,Public,1,Working,58.5,0,100.00
1,2,49,Tier5,5KW,31.7,9,439.97,2377,High,0,0,1,Highway,7,Working,47.0,0,96.36
2,3,35,Tier5,5KW,36.8,24,309.80,1905,Low,0,5,6,Highway,4,Working,53.5,1,100.00
3,4,63,Tier5,2KW,38.5,32,353.90,2074,Medium,0,1,31,Highway,1,Not Working,112.0,1,57.96
4,5,28,Tier1,5KW,33.2,8,597.43,1212,Medium,0,2,24,Private,6,Working,58.0,0,84.56

In [3]:
df.shape

(18946, 18)

# Basic checks

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18946 entries, 0 to 18945
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   User_ID                       18946 non-null  int64
 1   Age                           18946 non-null  int64
 2   City_Tier                     18946 non-null  str
 3   EV_Type                       18946 non-null  str
 4   Battery_Capacity_kWh          18946 non-null  float64
 5   Charging_Sessions_Per_Month   18946 non-null  int64
 6   Avg_Charge_Cost               18946 non-null  float64
 7   Distance_Travelled_Per_Month  18946 non-null  int64
 8   Income_Level                  18946 non-null  str
 9   Loan_Taken                    18946 non-null  int64
 10  Missed_Payments_Last_6M       18946 non-null  int64
 11  Tenure_Months                 18946 non-null  int64
 12  Charging_Location_Type        18946 non-null  str
 13  App_Usage_Score               18946 non-null  int64
 14  Charger_Working_Status        18946 non-null  str
 15  Charging_Time_Minutes         18946 non-null  float64
 16  High_Default_Risk             18946 non-null  int64
 17  Charging_Efficiency_Index     18946 non-null  float64
dtypes: float64(4), int64(9), str(5)
memory usage: 2.6 MB

In [5]:
df.describe(include="number")

,User_ID,Age,Battery_Capacity_kWh,Charging_Sessions_Per_Month,Avg_Charge_Cost,Distance_Travelled_Per_Month,Loan_Taken,Missed_Payments_Last_6M,Tenure_Months,App_Usage_Score,Charging_Time_Minutes,High_Default_Risk,Charging_Efficiency_Index
count,18946.000000,18946.000000,18946.000000,18946.000000,18946.000000,18946.000000,18946.000000,18946.000000,18946.000000,18946.000000,18946.000000,18946.000000,18946.000000
mean,9473.500000,42.919930,35.027890,19.496358,450.124728,1399.960044,0.408266,2.489866,24.096749,5.510767,62.940257,0.443999,87.653957
std,5469.383436,12.915867,10.047099,8.656905,120.149182,635.388130,0.491526,1.701978,13.583756,2.870352,32.274571,0.496867,25.041681
min,1.000000,21.000000,-8.000000,5.000000,-85.560000,300.000000,0.000000,0.000000,1.000000,1.000000,-14.100000,0.000000,0.000000
25%,4737.250000,32.000000,28.300000,12.000000,370.190000,848.250000,0.000000,1.000000,12.000000,3.000000,43.100000,0.000000,90.360000
50%,9473.500000,43.000000,35.100000,19.000000,449.640000,1399.500000,0.000000,2.000000,24.000000,6.000000,55.600000,0.000000,100.000000
75%,14209.750000,54.000000,41.900000,27.000000,530.467500,1951.000000,1.000000,4.000000,36.000000,8.000000,71.000000,1.000000,100.000000
max,18946.000000,65.000000,72.500000,34.000000,901.220000,2499.000000,1.000000,5.000000,47.000000,10.000000,278.200000,1.000000,100.000000

In [6]:
df.describe(include="object")

C:\Users\manis\AppData\Local\Temp\ipykernel_16052\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,City_Tier,EV_Type,Income_Level,Charging_Location_Type,Charger_Working_Status
count,18946,18946,18946,18946,18946
unique,5,4,3,3,2
top,Tier5,2KW,Medium,Highway,Working
freq,5716,7654,8586,6450,16094

In [7]:
df.isnull().sum()

User_ID                         0
Age                             0
City_Tier                       0
EV_Type                         0
Battery_Capacity_kWh            0
Charging_Sessions_Per_Month     0
Avg_Charge_Cost                 0
Distance_Travelled_Per_Month    0
Income_Level                    0
Loan_Taken                      0
Missed_Payments_Last_6M         0
Tenure_Months                   0
Charging_Location_Type          0
App_Usage_Score                 0
Charger_Working_Status          0
Charging_Time_Minutes           0
High_Default_Risk               0
Charging_Efficiency_Index       0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.columns

Index(['User_ID', 'Age', 'City_Tier', 'EV_Type', 'Battery_Capacity_kWh',
       'Charging_Sessions_Per_Month', 'Avg_Charge_Cost',
       'Distance_Travelled_Per_Month', 'Income_Level', 'Loan_Taken',
       'Missed_Payments_Last_6M', 'Tenure_Months', 'Charging_Location_Type',
       'App_Usage_Score', 'Charger_Working_Status', 'Charging_Time_Minutes',
       'High_Default_Risk', 'Charging_Efficiency_Index'],
      dtype='str')

# Input and output split

In [10]:
y=df['High_Default_Risk']
x=df.drop(columns=['High_Default_Risk','User_ID'])
print(y.shape)
print(x.shape)

(18946,)
(18946, 16)

# Feature Engineering
- Feature scaling  and encoding are done in the pipeline
- unecessary columns like user_id  are removed using domain knowledge

#as User_ID isan unneceesary column

# Train Test split`m

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(15156, 16)
(3790, 16)
(15156,)
(3790,)

In [12]:
num=x.select_dtypes(include="number").columns
cat=x.select_dtypes(include="object").columns

C:\Users\manis\AppData\Local\Temp\ipykernel_16052\3828830664.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat=x.select_dtypes(include="object").columns

In [13]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import GridSearchCV

# Data Preprocessing

In [14]:
num_pipe=Pipeline([("imputer",SimpleImputer(strategy="mean")),("scale",StandardScaler())])
cat_pipe=Pipeline([("imputer",SimpleImputer(strategy="most_frequent")),("encode",OneHotEncoder(handle_unknown="ignore"))])

In [15]:
preprocessing=ColumnTransformer([("num",num_pipe,num),("object",cat_pipe,cat)])
preprocessing

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scale', StandardScaler())]),
                                 Index(['Age', 'Battery_Capacity_kWh', 'Charging_Sessions_Per_Month',
       'Avg_Charge_Cost', 'Distance_Travelled_Per_Month', 'Loan_Taken',
       'Missed_Payments_Last_6M', 'Tenure_Months', 'App_Usage_Score',
       'Charging_Time_Minutes', 'Charging_Efficiency_Index'],
      dtype='str')),
                                ('object',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encode',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 Index(['City_Tier', 'EV_Type', 'Income_Level', 'Charging_Location_Type',
       'Charger_Working_Status'],
      dtype='str'))])

# Model Selection

In [16]:
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
models={"logistic":LogisticRegression(),"svm":SVC(),"random":RandomForestClassifier()}
results={}
for name,model in models.items():
    pipe=Pipeline([("preprocess",preprocessing),("model",model)])
    pipe.fit(x_train,y_train)
    y_pred=pipe.predict(x_test)
    y_pred_train=pipe.predict(x_train)
    test_score=accuracy_score(y_test,y_pred)
    train_score=accuracy_score(y_train,y_pred_train)
    results[name]={"train_score":train_score,"test_score":test_score}
print(results)

{'logistic': {'train_score': 0.9111902876748482, 'test_score': 0.908179419525066}, 'svm': {'train_score': 0.948535233570863, 'test_score': 0.9282321899736148}, 'random': {'train_score': 1.0, 'test_score': 0.9968337730870712}}

##  so the best_model here is random forest

# Model Training & Tuning

In [18]:
pipe=Pipeline([("prep",preprocessing),("model",RandomForestClassifier(class_weight="balanced",random_state=42))])

params={"model__n_estimators":[100,200],"model__max_depth":[5,8,10]}
grid=GridSearchCV(pipe,params,cv=3,n_jobs=-1)
grid.fit(x_train,y_train)

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('prep',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer()),
                                                                                         ('scale',
                                                                                          StandardScaler())]),
                                                                         Index(['Age', 'Battery_Capacity_kWh', 'Charging_Sessions_Per_Month',
       'Avg_Charge_Cost', 'Distance_Travelled_Per_Month', 'Loan_Taken',
       'Missed_Payments_Last_6M', 'Tenure_Months', 'App_Usage_Score...
                                                                                          SimpleImputer(strategy='most_frequent')),
                                                                                         ('encode',
                                                                                          OneHotEncoder(handle_unknown='ignore'))]),
                                                                         Index(['City_Tier', 'EV_Type', 'Income_Level', 'Charging_Location_Type',
       'Charger_Working_Status'],
      dtype='str'))])),
                                       ('model',
                                        RandomForestClassifier(class_weight='balanced',
                                                               random_state=42))]),
             n_jobs=-1,
             param_grid={'model__max_depth': [5, 8, 10],
                         'model__n_estimators': [100, 200]})

In [19]:
from sklearn.metrics import classification_report
best_model = grid.best_estimator_

y_pred_train = best_model.predict(x_train)
y_pred = best_model.predict(x_test)

accuracy_train = accuracy_score(y_train, y_pred_train)
accuracy = accuracy_score(y_test, y_pred)


classificationreport = classification_report(y_test, y_pred)

# Model Evaluation

In [20]:
print("training_accuracy",accuracy_train)
print("testing accuracy",accuracy)
print(classificationreport)

training_accuracy 1.0
testing accuracy 0.99155672823219
              precision    recall  f1-score   support

           0       1.00      0.99      0.99      2103
           1       0.98      1.00      0.99      1687

    accuracy                           0.99      3790
   macro avg       0.99      0.99      0.99      3790
weighted avg       0.99      0.99      0.99      3790

# saving the file

In [21]:
import joblib
joblib.dump(best_model,"model1.pkl")

['model.pkl']